export const contants = {
    HOSTING: 'https://hewe.club',
    STORAGE_KEY: 'token',
    LAST_POSITION_USER: 'lastPositionUser',
    APP_SCHEME: 'hewetoken://',
    screen: {
        HELLO: 'Hello',
        LOGIN: 'Login',
        SIGNUP: 'SignUp',
        FORGOTPASSWORD: 'ForgotPassword',
        HOME: 'Home',
        HOMESTACK: 'HomeStack',
        STARTRUN: 'StartRun',
        RUN_START: 'RunStart',
        PROFILE: 'Profile',
        PROFILE_STACK: 'ProfileStack',
        APPNAVIGATION: 'AppNavigation',
        HOMEDRAWER: 'HomeDrawer',
        RUN: 'Run',
        CHANGE_PASSWORD: 'ChangePassword',
        TRANSFER: 'Transfer',
        HISTORY_TRANSFER: 'HistoryTransfer',
        TOTAL_DISTANCE: 'TotalDistance',
        DISTANCE_DETAIL: 'DistanceDetail',
        KYC: 'KYC',
        AFFILIATE: 'Affiliate',
        SUPPORT: 'Support',
        REWARDHISTORY: 'RewardHistory',
        DELETE_ACCOUNT: 'DeleteAccount',
        WITHDRAW: 'Withdraw',
        HISTORY_WITHDRAW: 'HistoryWithdraw',
    }
}